### PR TITLE
Add support for Python 3

### PR DESCRIPTION
**Pull request by mptre**
An attempt to solve #2. Starting with the simplest solution, allowing
`%{}` to be used as the directive. The percent literal (`%`) will be
stripped of in the formatted string, but I prefer it be present in the
pattern for consistency.

Please give it a try using the pattern below and let me know what you
think:

```vim
autocmd FileType python let b:printf_pattern = 'print("%{}".format(%s))'
```

### CODE REVIEW

**Comment by mptre** [comment]
Ping @Alok @Ran4

**Comment by alok** [comment]
LGTM, with my limited knowledge of VimL. How would I test it out?

**Comment by mptre** [comment]
If you already have the repository cloned locally, then just checkout
this branch:

```sh
$ git pull --rebase
$ git checkout -b origin/python python
```

Otherwise, download the plugin and source it from Vim. But make sure to
not load any existing copy of vim-printf prior sourcing:

```sh
$ curl -o "${HOME}/printf.vim" https://raw.githubusercontent.com/mptre/vim-printf/python/plugin/printf.vim
```

... and then from vim:

```vim
:source ~/printf.vim
:autocmd FileType python let b:printf_pattern = 'print("%{}".format(%s))'
```

**Comment by Ran4** [comment]
As I said before, I'd much prefer

```
x, y
print("x: {}, y: {}".format(x, y))
```

or for a single variable, print("x: {}".format(x))

**Comment by mptre** [comment]
@Ran4: try the latest commit, it allows one to configure the delimiter:

```vim
au FileType python let b:printf_pattern = 'print("%{}".format(%s))'
  \ | let b:printf_delim = ': '
```

**Comment by alok** [comment]
LGTM.

**Comment by mptre** [comment]
Going through old PRs, I'm going to go ahead and close this for now.
Mainly because the pattern below works for both Python 2 and 3 and
`vim-printf` is intended to be used for debugging. This proposal is too
biased with respect to personal preferences IMHO. I'll leave the branch
around for a while in order to give people a chance to fork if they want
to keep it.

```vim
autocmd FileType python let b:printf_pattern = 'print("%s" %% (%s))'
```

**Pull request closed without merging**
